name: qalam_noor_parents
description: Qalam & Noor Mobile Application For Parents

publish_to: "none"

version: 0.0.1+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_keyboard_visibility: ^5.4.1
  flutter_screenutil: ^5.8.1
  font_awesome_flutter: ^10.4.0
  fpdart: ^0.6.0
  get: ^4.6.5
  http: ^0.13.6
  intl: ^0.18.1
  loading_animation_widget: ^1.2.0+4
  lottie: ^2.3.2
  shared_preferences: ^2.1.1
  shimmer: ^3.0.0

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Frutiger
      fonts:
        - asset: fonts/frutiger-light.ttf
          weight: 300
        - asset: fonts/frutiger-roman.ttf
          weight: 500
        - asset: fonts/frutiger-bold.ttf
          weight: 700
